/* Generated by Yosys 0.64 (git sha1 6d2c445ae-dirty, g++ 15.2.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -O3) [startdir/yosys at makepkg] */

module top(in0 , in1 , in2 , in3 , out0 , out1 );
  input in0 ;
  wire in0 ;
  input in1 ;
  wire in1 ;
  input in2 ;
  wire in2 ;
  input in3 ;
  wire in3 ;
  output out0 ;
  wire out0 ;
  output out1 ;
  wire out1 ;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  assign _09_ = ~in0 ;
  assign _10_ = ~in2 ;
  assign _11_ = ~in3 ;
  assign _00_ = ~in1 ;
  assign _01_ = ~(_09_ & in2 );
  assign _02_ = ~(in0  & _10_);
  assign out0  = ~(_01_ & _02_);
  assign _03_ = ~(in3  & _00_);
  assign _04_ = ~_03_;
  assign _05_ = ~(_02_ & _04_);
  assign _06_ = ~(_11_ & in1 );
  assign _07_ = ~_06_;
  assign _08_ = ~(_01_ & _07_);
  assign out1  = ~(_05_ & _08_);
endmodule

