/* Generated by Yosys 0.64 (git sha1 6d2c445ae-dirty, g++ 15.2.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -O3) [startdir/yosys at makepkg] */

module graph(in0, in1, in2, in3, out0, out1);
  input in0;
  wire in0;
  input in1;
  wire in1;
  input in2;
  wire in2;
  input in3;
  wire in3;
  output out0;
  wire out0;
  output out1;
  wire out1;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  assign _04_ = ~in0;
  assign _05_ = ~in1;
  assign out0 = ~(_04_ & in2);
  assign _00_ = ~(in1 & in3);
  assign _01_ = ~(in2 & in3);
  assign _02_ = ~(_05_ & _01_);
  assign _03_ = ~(_00_ & _02_);
  assign out1 = ~_03_;
endmodule

