/* Generated by Yosys 0.64 (git sha1 6d2c445ae-dirty, g++ 15.2.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -O3) [startdir/yosys at makepkg] */

module graph(in0, in1, in2, in3, out0, out1, out2);
  input in0;
  wire in0;
  input in1;
  wire in1;
  input in2;
  wire in2;
  input in3;
  wire in3;
  output out0;
  wire out0;
  output out1;
  wire out1;
  output out2;
  wire out2;
  wire _0_;
  wire _1_;
  assign _0_ = ~(in3 & in1);
  assign out2 = ~_0_;
  assign _1_ = ~(in2 & in0);
  assign out1 = ~_1_;
  assign out0 = 1'h1;
endmodule

