/* Generated by Yosys 0.64 (git sha1 6d2c445ae-dirty, g++ 15.2.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -O3) [startdir/yosys at makepkg] */

module graph(in0, in1, in2, in3, in4, in5, in6, in7, out0, out1, out2, out3, out4);
  input in0;
  wire in0;
  input in1;
  wire in1;
  input in2;
  wire in2;
  input in3;
  wire in3;
  input in4;
  wire in4;
  input in5;
  wire in5;
  input in6;
  wire in6;
  input in7;
  wire in7;
  output out0;
  wire out0;
  output out1;
  wire out1;
  output out2;
  wire out2;
  output out3;
  wire out3;
  output out4;
  wire out4;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  assign out4 = ~_03_;
  assign _04_ = ~(_01_ & _02_);
  assign _00_ = ~(_03_ & _04_);
  assign out3 = ~_00_;
  assign _01_ = ~in7;
  assign _02_ = ~in3;
  assign _03_ = ~(in7 & in3);
  assign out2 = 1'h1;
  assign out1 = in5;
  assign out0 = 1'h1;
endmodule

