/* Generated by Yosys 0.64 (git sha1 6d2c445ae-dirty, g++ 15.2.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -O3) [startdir/yosys at makepkg] */

module graph(in0, in1, in2, in3, in4, in5, in6, in7, out0, out1, out2, out3, out4);
  input in0;
  wire in0;
  input in1;
  wire in1;
  input in2;
  wire in2;
  input in3;
  wire in3;
  input in4;
  wire in4;
  input in5;
  wire in5;
  input in6;
  wire in6;
  input in7;
  wire in7;
  output out0;
  wire out0;
  output out1;
  wire out1;
  output out2;
  wire out2;
  output out3;
  wire out3;
  output out4;
  wire out4;
  wire _0_;
  wire _1_;
  wire _2_;
  assign _0_ = ~in7;
  assign _1_ = ~in3;
  assign out4 = ~(_0_ & _1_);
  assign _2_ = ~(in7 & in3);
  assign out3 = ~(out4 & _2_);
  assign out2 = 1'h0;
  assign out1 = in5;
  assign out0 = 1'h0;
endmodule

