/* Generated by Yosys 0.64 (git sha1 6d2c445ae-dirty, g++ 15.2.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -O3) [startdir/yosys at makepkg] */

module top(in0 , in1 , in2 , in3 , out0 , out1 , out2 , out3 );
  input in0 ;
  wire in0 ;
  input in1 ;
  wire in1 ;
  input in2 ;
  wire in2 ;
  input in3 ;
  wire in3 ;
  output out0 ;
  wire out0 ;
  output out1 ;
  wire out1 ;
  output out2 ;
  wire out2 ;
  output out3 ;
  wire out3 ;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  assign _10_ = ~(in0  & in2 );
  assign out0  = ~_10_;
  assign _00_ = ~(in1  & in3 );
  assign _01_ = ~_00_;
  assign _02_ = ~(_10_ & _01_);
  assign out2  = ~_02_;
  assign _03_ = ~(in0  & in3 );
  assign _04_ = ~_03_;
  assign _05_ = ~(in2  & in1 );
  assign _06_ = ~_05_;
  assign _07_ = ~(_04_ & _06_);
  assign out3  = ~_07_;
  assign _08_ = ~(_03_ & _05_);
  assign _09_ = ~(_07_ & _08_);
  assign out1  = ~_09_;
endmodule

