/* Generated by Yosys 0.64 (git sha1 6d2c445ae-dirty, g++ 15.2.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -O3) [startdir/yosys at makepkg] */

module top(in0, in1, in2, in3, out0, out1, out2, out3);
  input in0;
  wire in0;
  input in1;
  wire in1;
  input in2;
  wire in2;
  input in3;
  wire in3;
  output out0;
  wire out0;
  output out1;
  wire out1;
  output out2;
  wire out2;
  output out3;
  wire out3;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  assign _08_ = ~(in0 & in2);
  assign out0 = ~_08_;
  assign _00_ = ~(in3 & in1);
  assign _01_ = ~_00_;
  assign _02_ = ~(in0 & in3);
  assign _03_ = ~(in2 & in1);
  assign _04_ = ~(out0 & _01_);
  assign out3 = ~_04_;
  assign _05_ = ~(_02_ & _03_);
  assign _06_ = ~(_04_ & _05_);
  assign out1 = ~_06_;
  assign _07_ = ~(_08_ & _01_);
  assign out2 = ~_07_;
endmodule

